# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add <- function(a, b) {
    .Call('_cpptest_add', PACKAGE = 'cpptest', a, b)
}

do_double <- function(x) {
    .Call('_cpptest_do_double', PACKAGE = 'cpptest', x)
}

modify_std_vector <- function(vector) {
    .Call('_cpptest_modify_std_vector', PACKAGE = 'cpptest', vector)
}

get_array <- function() {
    invisible(.Call('_cpptest_get_array', PACKAGE = 'cpptest'))
}

push_array <- function(arr) {
    .Call('_cpptest_push_array', PACKAGE = 'cpptest', arr)
}

push_list_arrays <- function(lst) {
    .Call('_cpptest_push_list_arrays', PACKAGE = 'cpptest', lst)
}

test_1d_arrays <- function(arr_list) {
    invisible(.Call('_cpptest_test_1d_arrays', PACKAGE = 'cpptest', arr_list))
}

test_2d_arrays <- function(arr_list, dimensions) {
    invisible(.Call('_cpptest_test_2d_arrays', PACKAGE = 'cpptest', arr_list, dimensions))
}

